ckpt_epoch: null
exp_name: ???
target_sec: 4
batch_size: 128
phoneme_loss_weight: 0.5
debug: False
num_workers: 16

defaults:
  - common.yaml
  - trainer: trainer
  - optimizer: adamw
  - emg_enc: enc
  - feature: hubert
