exp_name: ???
ckpt_epoch: null
batch_size: 64
num_workers: 16
debug: False
merge: False
max_len: 1024
model_name: "allenai/longformer-base-4096"
learning_rate: 1e-4
lora_r: 8
lora_alpha: 32
lora_dropout: 0.1
vocab_size: 1026

defaults:
  - common.yaml
